### ISSUE TITLE
Not possible to query strings that have pipe-characters

### ISSUE THREAD

**Issue by kingOttmar** [patrickTingen/DataDigger#23]
Entering "O|722246,0003" in a filter field triggers an error (query fill-in turns yellow).
** Compilation error at -- "O|722246,0003) BY 722246"

**Comment by patrickTingen** [comment]
Hi, thanks for reporting this and thanks for using the DataDigger. This bug occurs because internally, the DataDigger uses the pipe symbol to handle query sorting. I have fixed this already for the coming release but a quick fix is attached to this message. 

Unzip it and copy it to the DataDigger folder. After restarting DataDigger it will recompile itself and you will be able to use the pipe symbol in your query.

[wDataDigger.zip](https://github.com/patrickTingen/DataDigger/files/1474567/wDataDigger.zip)
