### ISSUE TITLE
DataDigger doesn't start when user ini file is missing

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#32]
Latest dev version
I deleted the DataDigger-username.ini file and now Datadigger doesn't start anymore.
Same thing happens when i try to use the Workfolder setting since it is just an empty folder at the first start.

![grafik](https://user-images.githubusercontent.com/13309951/44085780-ce07a19e-9fba-11e8-86a9-96eb2f366072.png)

**Comment by patrickTingen** [comment]
Hi Alexander,

I tried to reproduce the issue, but could not. Can you give me some more
info so I can reproduce it?
Every time I deleted the user-ini, it got re-created. Both with the
'WorkFolder' setting in DataDigger.ini and without.


gr

Patrick Tingen


Op di 14 aug. 2018 om 12:09 schreef movedoa <notifications@github.com>:

**Comment by movedoa** [comment]
Tracked it down, the error happens when the settings cache is set to no

```
[DataDigger:Cache]
Settings=no
```

**Comment by patrickTingen** [comment]
This is a nasty one and probably did not work good in older versions as
well. The problem is that the option gives the idea that you can bypass the
caching of the setting (hence the name). But in reality this is hardly
doable in the current codebase, nor is it needed, I think. Did you
encounter this while testing or did you also use it in previous versions?

At the moment I am considering taking it out, unless you can convince me
with a good usecase. The reason it was there in the first place was because
I was not too confident that the caching mechanism would work, so it was an
easy way to turn it off. Mind you: this was DD18 of june 2013. In DD24 you
have the option to specify another folder as workfolder, so if you really
do not want to / cannot write to the main DD folder, then there are other
ways to achieve that.

Removing it would simplify the codebase, which I think is a Good Thing™

gr
Patrick Tingen


Op do 16 aug. 2018 om 11:41 schreef movedoa <notifications@github.com>:

**Comment by patrickTingen** [comment]
Merging all settings is something I will keep in mind for a next version. For this version this would be a too big change. I removed the option to suppress settings caching
