### ISSUE TITLE
DataDigger:Update cannot be set in DataDigger ini

### ISSUE THREAD

**Issue by movedoa** [patrickTingen/DataDigger#37]
Since i deploy a specific version to a location where there is no interenet connection sometimes i want to set the default update channel to stable manual (channel 0)

I put the following setting in the DataDigger.ini
```
[DataDigger:Update]
UpdateChannel=0
```

But when i start DataDigger and close it again, the settings is gone
Then the next user without user.ini gets channel 1 not 0

**Comment by patrickTingen** [comment]
Found it, reproduced it and fixed it. The bug was in the conversion part of the settings. This loops from the last used version to the current, converting what is needed. Point is, if you have not run it before, the last-used version was set to zero, thus resulting in performing all settings conversions, which were not needed in the first place. One of the conversions for DD19 was setting UpdateChannel to 1. 

I now check if DD has been used before. If not, no conversion is needed, which is also good for shortening startup time.
